name: Joejag - Just Another Geek
markdown: kramdown
future: true
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]

highligher: true
permalink: /:year/:title.html
gems:
  - jekyll-redirect-from

url: http://www.joejjag.com