# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.6.5

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "38:80:f2:92:4e:5b:cc:4b:a5:2e:06:0c:75:c7:e7:72"
      - checkout
      - run: sudo apt install libpopt0 
      - run: curl -sLO http://cdn-fastly.deb.debian.org/debian/pool/main/r/rsync/rsync_3.1.3-6_amd64.deb && sudo dpkg -i rsync_3.1.3-6_amd64.deb
      - run: gem install bundler -v 2.0.2
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run: bundle exec jekyll build
      - run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" _site/ ubuntu@joejag.com:/home/ubuntu/sites/www.joejag.com
      